//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omnipaste.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Omnipaste.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me why.
        /// </summary>
        public static string ActivationFailedHeader {
            get {
                return ResourceManager.GetString("ActivationFailedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry master we failed, please don&apos;t kill us!.
        /// </summary>
        public static string ActivationFailedLabel {
            get {
                return ResourceManager.GetString("ActivationFailedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations Omnipaste was installed successfully on your PC..
        /// </summary>
        public static string AndroidInstallGuideLabel1 {
            get {
                return ResourceManager.GetString("AndroidInstallGuideLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next, we need to install Omnipaste on your Android device. Please use this link to install the application from Google Play:.
        /// </summary>
        public static string AndroidInstallGuideLabel2 {
            get {
                return ResourceManager.GetString("AndroidInstallGuideLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll wait for you to do that and once you install the app, your devices will be automatically linked together, allowing you to copy-paste and receive notifications between them..
        /// </summary>
        public static string AndroidInstallGuideLabel4 {
            get {
                return ResourceManager.GetString("AndroidInstallGuideLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnipaste.
        /// </summary>
        public static string AplicationName {
            get {
                return ResourceManager.GetString("AplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Required.
        /// </summary>
        public static string AuthenticationRequired {
            get {
                return ResourceManager.GetString("AuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization code.
        /// </summary>
        public static string AuthorizationCode {
            get {
                return ResourceManager.GetString("AuthorizationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with the server is broken. Please try again later..
        /// </summary>
        public static string BrokenCommunicationError {
            get {
                return ResourceManager.GetString("BrokenCommunicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string ButtonAuthenticate {
            get {
                return ResourceManager.GetString("ButtonAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string ButtonReply {
            get {
                return ResourceManager.GetString("ButtonReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string ButtonRetry {
            get {
                return ResourceManager.GetString("ButtonRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ButtonSend {
            get {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone will start calling soon. Please pick it up..
        /// </summary>
        public static string CallingLabel {
            get {
                return ResourceManager.GetString("CallingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no clippings. To add some, simply copy a text the way you usually do. It will automatically appear here so that you can paste it on your other devices that are connected on Omnipaste..
        /// </summary>
        public static string ClippingListEmptyLabel {
            get {
                return ResourceManager.GetString("ClippingListEmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New clipping.
        /// </summary>
        public static string ClippingNotificationTitle {
            get {
                return ResourceManager.GetString("ClippingNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for you to create your first clipping from your Android device..
        /// </summary>
        public static string CongratulationsContent {
            get {
                return ResourceManager.GetString("CongratulationsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, your devices are now linked..
        /// </summary>
        public static string CongratulationsHeader {
            get {
                return ResourceManager.GetString("CongratulationsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appbar_connect.
        /// </summary>
        public static string ConnectIcon {
            get {
                return ResourceManager.GetString("ConnectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectionConnect {
            get {
                return ResourceManager.GetString("ConnectionConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string ConnectionDisconnect {
            get {
                return ResourceManager.GetString("ConnectionDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reach the Omnipaste server. Please try again or check the connection settings bellow..
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string ConnectionSettingsHeader {
            get {
                return ResourceManager.GetString("ConnectionSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Troubleshooter.
        /// </summary>
        public static string ConnectionTroubleshooter {
            get {
                return ResourceManager.GetString("ConnectionTroubleshooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start.
        /// </summary>
        public static string ContextMenuAutoStart {
            get {
                return ResourceManager.GetString("ContextMenuAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Synchronization.
        /// </summary>
        public static string ContextMenuStopSync {
            get {
                return ResourceManager.GetString("ContextMenuStopSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appbar_disconnect.
        /// </summary>
        public static string DisconnectIcon {
            get {
                return ResourceManager.GetString("DisconnectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismis.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token empty in GetRemoteConfiguration.GetExecuteResult - Problem in the API.
        /// </summary>
        public static string EmptyTokenFromServer {
            get {
                return ResourceManager.GetString("EmptyTokenFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &quot;via Omnipaste&quot; to SMS.
        /// </summary>
        public static string EnableSMSBranding {
            get {
                return ResourceManager.GetString("EnableSMSBranding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events to display..
        /// </summary>
        public static string EventListEmpty {
            get {
                return ResourceManager.GetString("EventListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call back.
        /// </summary>
        public static string EventTooltipCallBack {
            get {
                return ResourceManager.GetString("EventTooltipCallBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply with SMS.
        /// </summary>
        public static string EventTooltipReply {
            get {
                return ResourceManager.GetString("EventTooltipReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered while validating authentication code.
        /// </summary>
        public static string ExceptionDuringAuthentication {
            get {
                return ResourceManager.GetString("ExceptionDuringAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Link.
        /// </summary>
        public static string HyperlinkNotificationTitle {
            get {
                return ResourceManager.GetString("HyperlinkNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call ended.
        /// </summary>
        public static string IncommingCallNotificationCallEnded {
            get {
                return ResourceManager.GetString("IncommingCallNotificationCallEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Call.
        /// </summary>
        public static string IncommingCallNotificationEndCall {
            get {
                return ResourceManager.GetString("IncommingCallNotificationEndCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Text.
        /// </summary>
        public static string IncommingCallNotificationSendSms {
            get {
                return ResourceManager.GetString("IncommingCallNotificationSendSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming call from .
        /// </summary>
        public static string IncommingCallNotificationTitle {
            get {
                return ResourceManager.GetString("IncommingCallNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming SMS from .
        /// </summary>
        public static string IncommingSmsNotificationTitle {
            get {
                return ResourceManager.GetString("IncommingSmsNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string LoadingLabel {
            get {
                return ResourceManager.GetString("LoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clippings.
        /// </summary>
        public static string MasterClippingListDisplayName {
            get {
                return ResourceManager.GetString("MasterClippingListDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MasterClippingListHeaderAll {
            get {
                return ResourceManager.GetString("MasterClippingListHeaderAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        public static string MasterClippingListHeaderCloud {
            get {
                return ResourceManager.GetString("MasterClippingListHeaderCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string MasterClippingListHeaderLocal {
            get {
                return ResourceManager.GetString("MasterClippingListHeaderLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string MasterEventListDisplayName {
            get {
                return ResourceManager.GetString("MasterEventListDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MasterEventListHeaderAll {
            get {
                return ResourceManager.GetString("MasterEventListHeaderAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Calls.
        /// </summary>
        public static string MasterEventListHeaderCalls {
            get {
                return ResourceManager.GetString("MasterEventListHeaderCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Messages.
        /// </summary>
        public static string MasterEventListHeaderSms {
            get {
                return ResourceManager.GetString("MasterEventListHeaderSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty authorization code given. Please use a non empty authorization code..
        /// </summary>
        public static string MissingUserTokenError {
            get {
                return ResourceManager.GetString("MissingUserTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No proxy server is used. A direct connection is made to the Omnipaste server..
        /// </summary>
        public static string NoProxyUsed {
            get {
                return ResourceManager.GetString("NoProxyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance is already running. Check for the tray icon..
        /// </summary>
        public static string OtherInstanceRunning {
            get {
                return ResourceManager.GetString("OtherInstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to contact Omnipaste server..
        /// </summary>
        public static string PingingHome {
            get {
                return ResourceManager.GetString("PingingHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        public static string ProxyHost {
            get {
                return ResourceManager.GetString("ProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number:.
        /// </summary>
        public static string ProxyPort {
            get {
                return ResourceManager.GetString("ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Type.
        /// </summary>
        public static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string ProxyUsername {
            get {
                return ResourceManager.GetString("ProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is how a local clipping looks like.
        /// </summary>
        public static string SampleLocalClipping {
            get {
                return ResourceManager.GetString("SampleLocalClipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via Omnipaste.
        /// </summary>
        public static string SentFromOmnipaste {
            get {
                return ResourceManager.GetString("SentFromOmnipaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appbar_cogs.
        /// </summary>
        public static string SettingsIconName {
            get {
                return ResourceManager.GetString("SettingsIconName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string SettingsLogOut {
            get {
                return ResourceManager.GetString("SettingsLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omnipaste is still running. To open the window again, double-click the icon..
        /// </summary>
        public static string ShellBallonContent {
            get {
                return ResourceManager.GetString("ShellBallonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running in the background.
        /// </summary>
        public static string ShellBallonTitle {
            get {
                return ResourceManager.GetString("ShellBallonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string SmsComposerLabelMessage {
            get {
                return ResourceManager.GetString("SmsComposerLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients.
        /// </summary>
        public static string SmsComposerLabelRecepients {
            get {
                return ResourceManager.GetString("SmsComposerLabelRecepients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending ....
        /// </summary>
        public static string SmsComposerSending {
            get {
                return ResourceManager.GetString("SmsComposerSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent successfully.
        /// </summary>
        public static string SmsComposerSuccess {
            get {
                return ResourceManager.GetString("SmsComposerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS.
        /// </summary>
        public static string SmsComposerTitle {
            get {
                return ResourceManager.GetString("SmsComposerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect, you need an authorization code. You can get one from the.
        /// </summary>
        public static string UserTokenLabel1 {
            get {
                return ResourceManager.GetString("UserTokenLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website..
        /// </summary>
        public static string UserTokenLabel2 {
            get {
                return ResourceManager.GetString("UserTokenLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
