//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniDebug.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmniDebug.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipping Content.
        /// </summary>
        public static string ClippingContent {
            get {
                return ResourceManager.GetString("ClippingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipping Type.
        /// </summary>
        public static string ClippingType {
            get {
                return ResourceManager.GetString("ClippingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appbar_futurama_bender.
        /// </summary>
        public static string DebugIconName {
            get {
                return ResourceManager.GetString("DebugIconName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string NotificationContactName {
            get {
                return ResourceManager.GetString("NotificationContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string NotificationContent {
            get {
                return ResourceManager.GetString("NotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string NotificationPhoneNumber {
            get {
                return ResourceManager.GetString("NotificationPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Time.
        /// </summary>
        public static string NotificationTime {
            get {
                return ResourceManager.GetString("NotificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appbar_phone.
        /// </summary>
        public static string PhoneIcon {
            get {
                return ResourceManager.GetString("PhoneIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate call notification.
        /// </summary>
        public static string SimulateCallNotification {
            get {
                return ResourceManager.GetString("SimulateCallNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate incoming clipping.
        /// </summary>
        public static string SimulateIncomingClipping {
            get {
                return ResourceManager.GetString("SimulateIncomingClipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate SMS notification.
        /// </summary>
        public static string SimulateSMSNotification {
            get {
                return ResourceManager.GetString("SimulateSMSNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appbar_email_minimal.
        /// </summary>
        public static string SMSIcon {
            get {
                return ResourceManager.GetString("SMSIcon", resourceCulture);
            }
        }
    }
}
