﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using global::PhoneCalls.Models;
using OmniApi.Models;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace PhoneCalls.Resources.v1
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIPhoneCallsApi : IPhoneCallsApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIPhoneCallsApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual IObservable<PhoneCall> Get(string id,string token)
        {
            var arguments = new object[] { id,token };
            return (IObservable<PhoneCall>) methodImpls["Get"](Client, arguments);
        }

        public virtual IObservable<PhoneCall> Create(PhoneCall payload,string token)
        {
            var arguments = new object[] { payload,token };
            return (IObservable<PhoneCall>) methodImpls["Create"](Client, arguments);
        }

        public virtual IObservable<EmptyModel> Patch(string id,object payload,string token)
        {
            var arguments = new object[] { id,payload,token };
            return (IObservable<EmptyModel>) methodImpls["Patch"](Client, arguments);
        }

    }
}


