﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using global::Contacts.Dto;
using global::Contacts.Models;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace Contacts.Api.Resources.v1
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIContactsApi : IContactsApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIContactsApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual IObservable<ContactDto> Get(string id,string token)
        {
            var arguments = new object[] { id,token };
            return (IObservable<ContactDto>) methodImpls["Get"](Client, arguments);
        }

        public virtual IObservable<List<ContactDto>> GetUpdates(string from,string token)
        {
            var arguments = new object[] { from,token };
            return (IObservable<List<ContactDto>>) methodImpls["GetUpdates"](Client, arguments);
        }

    }
}


