//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmniHolidays.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmniHolidays.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a different category or language.
        /// </summary>
        public static string ChooseOtherTemplateLabel {
            get {
                return ResourceManager.GetString("ChooseOtherTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleagues.
        /// </summary>
        public static string Colleagues {
            get {
                return ResourceManager.GetString("Colleagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a personalized greeting to your co-workers!.
        /// </summary>
        public static string ColleaguesTemplateInfo {
            get {
                return ResourceManager.GetString("ColleaguesTemplateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ContactListHeader {
            get {
                return ResourceManager.GetString("ContactListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the contacts to whom you want to send the SMS.
        /// </summary>
        public static string ContactListSubHeader {
            get {
                return ResourceManager.GetString("ContactListSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a custom greeting for your family!.
        /// </summary>
        public static string FamilyTemplateInfo {
            get {
                return ResourceManager.GetString("FamilyTemplateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems it&apos;s taking longer then usual to fetch your contacts.
        ///Please make sure your phone is on or try again..
        /// </summary>
        public static string FetchContactsTakingLong {
            get {
                return ResourceManager.GetString("FetchContactsTakingLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching your contacts....
        /// </summary>
        public static string FetchingContacts {
            get {
                return ResourceManager.GetString("FetchingContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a custom greeting for your friends!.
        /// </summary>
        public static string FriendsTemplateInfo {
            get {
                return ResourceManager.GetString("FriendsTemplateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Greeting for.
        /// </summary>
        public static string GreetingHeader {
            get {
                return ResourceManager.GetString("GreetingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greeting Language:.
        /// </summary>
        public static string GreetingLanguageLabel {
            get {
                return ResourceManager.GetString("GreetingLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        public static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent successfully!.
        /// </summary>
        public static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names will be added automatically in the blank space..
        /// </summary>
        public static string PlaceholderInfo {
            get {
                return ResourceManager.GetString("PlaceholderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        public static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string RetryFetchContacts {
            get {
                return ResourceManager.GetString("RetryFetchContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string Romanian {
            get {
                return ResourceManager.GetString("Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a personalized greeting to your classmates!.
        /// </summary>
        public static string SchoolTemplateInfo {
            get {
                return ResourceManager.GetString("SchoolTemplateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is how your message will look:.
        /// </summary>
        public static string SendingMessageContentHeader {
            get {
                return ResourceManager.GetString("SendingMessageContentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending the message bellow to the.
        /// </summary>
        public static string SendingMessagePart1 {
            get {
                return ResourceManager.GetString("SendingMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacts that you selected.
        /// </summary>
        public static string SendingMessagePart2 {
            get {
                return ResourceManager.GetString("SendingMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via Omnipaste.
        /// </summary>
        public static string SentFromOmnipaste {
            get {
                return ResourceManager.GetString("SentFromOmnipaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To: .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
    }
}
